#ifndef __QFC_GITVERSION_HPP__
#define __QFC_GITVERSION_HPP__

#define GIT_COMMITHASH			""
#define GIT_COMMITHASHSHORT		""
#define GIT_COMMITTERDATE		""
#define GIT_ROLLINGCOUNT		0

#define GIT_MAJOR_BUILD_VERSION		0
#define GIT_MINOR_BUILD_VERSION		0
#define GIT_REVISION_BUILD_NUM		0
#define GIT_BUILD_NUM				0
#define GIT_BUILD_VERSION			"0.0.0.0"
#define GIT_TAG_NAME				""
#define GIT_BRANCH					"HEAD"

#endif
